name: practice
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.24.2
  firebase_analytics: ^10.8.0
  cloud_firestore: ^4.13.6
  firebase_auth: ^4.16.0
  google_sign_in: ^6.1.6
  font_awesome_flutter: 10.6.0
  provider: ^6.0.3
  shared_preferences: ^2.0.9
  cupertino_icons: ^1.0.2
  #http: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    #- assets/1.jpg
    - assets/gulambi.png
    - assets/google.png
